inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-discourse: default.yml

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true

AllCops:
  NewCops: enable

RSpec:
  Enabled: true
